# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf2403df3ac6230ec2fcb852ef511d772ee33d0c02c186fd2d35f37520475d02dadd2434ba04ba4b8229e281a01e3c7102e5ae2f0bc75408f381a24fb62c5d87

test:
  secret_key_base: 8a275c1c52d33191db87d0cf48f603d0eac4df81ca734b4bd8d2e142e429f58da1f6d45fce07df79bbe2b59fbe4b1e30d11d0509a4c17ffba41ba430f6a07bb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
